INSERT INTO pandemic_version (version_name) VALUES ('Pandemic');
INSERT INTO pandemic_version (version_name) VALUES ('Pandemic: On the Brink'); 
INSERT INTO pandemic_version (version_name) VALUES ('Pandemic: State of Emergency');
INSERT INTO pandemic_version (version_name) VALUES ('Pandemic: In the Lab'); 

INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Contingency Planner', 'The Contingency Planner may, as an action, take an Event card from anywhere in the Player Discard Pile and place it on his Role card. Only 1 Event card can be on his role card at a time. It does not count against his hand limit. When the Contingency Planner plays the Event card on his role card remove this Event card from the game (instead of discarding it).');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Dispatcher', 'The Dispatcher may, as an action, either: move any pawn, if its owner agrees, to any city containing another pawn, or move another player''s pawn, if its owner agrees, as if it were his own. The Dispatcher can only move other players'' pawns; he may not direct them to do other actions, such as Treat Disease.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Medic', 'The Medic removes all cubes, not 1, of the same color when doing the Treat Disease action. If a disease has been cured, he automatically removes all cubes of that color from a city, simply by entering it or being there. This does not take an action. The Medic also prevents placing disease cubes (and outbreaks) of cured diseases in his location.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Operations Expert', 'The Operations Expert may, as an action, either: build a research station in his current city without discarding (or using) a City card, or once per turn, move from a research station to any city by discarding any City card.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Quarantine Specialist', 'The Quarantine Specialist prevents both outbreaks and the placement of disease cubes in the city she is in and all cities connected to that city. She does not affect cubes placed during setup.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Researcher', 'When doing the Share Knowledge action, the Researcher may give any City card from her hand to another player in the same city as her, without this card having to match her city. The transfer must be from her hand to the other player''s hand, but it can occur on either player''s turn.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (1, 'Scientist', 'The Scientist needs only 4 (not 5) City cards of the same disease color to Discover a Cure for that disease.');

INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Bio-Terrorist', 'The Bio-Terrorist is used only in the Bio-Terrorist challenge.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Archivist', 'The Archivist''s hand limit is 8 cards. He may, once per turn, as an action, draw the City card that matches the city he is in from the Player Discard Pile into his hand.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Containment Specialist', 'When the Containment Specialist enters a city, if 2 or more disease cubes of the same color are present, he removes 1 of them.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Epidemiologist', 'The Epidemiologist, once per turn and on her turn (only), may take any City card from a player in the same city. The other player must agree. Doing this is not an action.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Field Operative', 'The Field Operative may, once per turn as an action, move 1 disease cube from the city he is in and place it as a sample on his role card. When he Discovers a Cure, he may replace exactly 2 of the needed City cards by returning 3 cubes of the cure color from his Role card to the supply.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Generalist', 'The Generalist may do up to 5 actions each turn.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (2, 'Troubleshooter', 'The Troubleshooter, at the start of her turn, looks at as many Infection cards as the current infection rate (by taking them from the top of the Infection Deck, looking at them, and putting them back in the same order). When moving to a city via a Direct Flight, the Troubleshooter reveals the City card used to the other players (but does not discard it). She may do this when moving other pawns via the Event Special Orders, but not when being moved by other players.');

INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (3, 'Colonel', 'Use this role only with Quarantines. During setup, add 2 more quarantine markers to the supply. When he enters a city with a "1" quarantine marker, flip it to its "2" side. As an action, he may discard a city card to place a quarantine marker in any city.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (3, 'First Responder', 'As an action, she may move to any city with a research station. After resolving an Epidemic, she may - out of turn - move to the epidemic city and Treat Disease there (before Infections). The ''epidemic city'' is the city matching the card drawn from the bottom of the Infection deck during the Infect step of resolving the Epidemic.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (3, 'Gene Splicer', 'She may Discover a Cure at a research station in a city of the color being cured by turning in 2 City cards of the cure color, plus 1 City card each of the 3 other (standard) disease colors.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (3, 'Pharmacist', 'As an action, he may reveal a city card to Treat Disease (or Distribute Vaccine in the Superbug challenge) in that city. He must discard a vaccine dose to Distribute Vaccine. As an action, he may remove 1 cube of a cured disease from any city to the supply.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (3, 'Veterinarian', 'Use this role only in the Hinterlands challenge. As an action at a research station, he may move to any Hinterlands space. In a Hinterlands space, he removes 2 cubes of an uncured disease with Treat Disease (if 2 or more cubes are there).');

INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (4, 'Field Director', 'The Field Director may: Treat Disease in a city connected to the city he is in (instead of the city he is in), or move another player''s pawn in his city, or a city connected to it, once per turn by Drive/Ferry, as a free bonus action. He must get permission before moving another player''s pawn.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (4, 'Local Liaison', 'The Local Liaison may give a city card that matches the color of the city she is in to a player in any city of the same color. Doing this is an action, which she may do once a turn and only on her turn. In the Lab challenge, she may either Characterize a Disease or Test a Cure as a free bonus action, once during her turn, at a research station.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (4, 'Pilot', 'The Pilot may not do any movement actions (Drive/Ferry or Flights), nor build research stations. He may, as an action, fly to any city within 3 connections, skipping cities in between. He may take along 1 other pawn as a passenger.');
INSERT INTO pandemic_roles (version_id,	role_name, abilities) VALUES (4, 'Virologist', 'The Virologist may discard: 2 City cards of the same color to replace 1 City card of the cure color, when she Discovers a Cure, or 1 City card, as an action, to remove 1 cube of its color from any city, returning it to the supply.');
